services:
  # Frontend: Static Site
  - type: static
    name: bone-fracture-detects-web
    env: static
    buildCommand: npm run build
    publishPath: build
    baseDir: bone-fracture-web
    envVars:
      - key: REACT_APP_API_URL
        value: https://bone-fracture-backend-or69.onrender.com

  # Backend: Django Web Service
  - type: web
    name: bone-fracture-detects-api
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn server.wsgi:application
    baseDir: backend
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: server.settings
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: bone-fracture-backend-or69.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://bone-fracture-frontend.onrender.com
